# Generated by Django 5.1.4 on 2025-01-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diabetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fastin_sugar', models.IntegerField(blank=True, default=0, null=True, verbose_name='Fasting Sugar')),
                ('random_sugar', models.IntegerField(blank=True, default=0, null=True, verbose_name='Random Sugar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Noted At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update At')),
            ],
        ),
    ]
