# Generated by Django 5.1.4 on 2025-01-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0002_rename_fastin_sugar_diabetes_fasting_sugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabetes',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Noted At'),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Update At'),
        ),
    ]
