# Generated by Django 5.0.2 on 2025-01-31 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic', models.IntegerField(default=0, verbose_name='Systolic')),
                ('diastolic', models.IntegerField(default=0, verbose_name='Diastolic')),
                ('timing', models.CharField(choices=[('morning', 'morning'), ('afternoon', 'afternoon'), ('evening', 'evening')], max_length=20, verbose_name='Time')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Noted At')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Update At')),
            ],
        ),
    ]
